version: '3.6'

services:
  api:
    build: ./project
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://silab:silab@db/silab
    networks:
      - default
    ports:
      - 4000:4000
    volumes:
      - ./project:/usr/src/app/project
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: silab
      POSTGRES_PASSWORD: silab
      POSTGRES_DB: silab
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data